/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SyDleAppRoot {
    }
    interface SyDleBadCls {
    }
    interface SyDleBadInp {
    }
    interface SyDleBadLcpImage {
    }
    interface SyDleBadLcpWillload {
    }
    interface SyDleExample {
    }
    interface SyDleGoodCls {
    }
    interface SyDleGoodInp {
    }
    interface SyDleGoodLcpImage {
    }
    interface SyDleGoodLcpWillload {
    }
    interface SyDleMediumLcpWillload {
    }
}
declare global {
    interface HTMLSyDleAppRootElement extends Components.SyDleAppRoot, HTMLStencilElement {
    }
    var HTMLSyDleAppRootElement: {
        prototype: HTMLSyDleAppRootElement;
        new (): HTMLSyDleAppRootElement;
    };
    interface HTMLSyDleBadClsElement extends Components.SyDleBadCls, HTMLStencilElement {
    }
    var HTMLSyDleBadClsElement: {
        prototype: HTMLSyDleBadClsElement;
        new (): HTMLSyDleBadClsElement;
    };
    interface HTMLSyDleBadInpElement extends Components.SyDleBadInp, HTMLStencilElement {
    }
    var HTMLSyDleBadInpElement: {
        prototype: HTMLSyDleBadInpElement;
        new (): HTMLSyDleBadInpElement;
    };
    interface HTMLSyDleBadLcpImageElement extends Components.SyDleBadLcpImage, HTMLStencilElement {
    }
    var HTMLSyDleBadLcpImageElement: {
        prototype: HTMLSyDleBadLcpImageElement;
        new (): HTMLSyDleBadLcpImageElement;
    };
    interface HTMLSyDleBadLcpWillloadElement extends Components.SyDleBadLcpWillload, HTMLStencilElement {
    }
    var HTMLSyDleBadLcpWillloadElement: {
        prototype: HTMLSyDleBadLcpWillloadElement;
        new (): HTMLSyDleBadLcpWillloadElement;
    };
    interface HTMLSyDleExampleElement extends Components.SyDleExample, HTMLStencilElement {
    }
    var HTMLSyDleExampleElement: {
        prototype: HTMLSyDleExampleElement;
        new (): HTMLSyDleExampleElement;
    };
    interface HTMLSyDleGoodClsElement extends Components.SyDleGoodCls, HTMLStencilElement {
    }
    var HTMLSyDleGoodClsElement: {
        prototype: HTMLSyDleGoodClsElement;
        new (): HTMLSyDleGoodClsElement;
    };
    interface HTMLSyDleGoodInpElement extends Components.SyDleGoodInp, HTMLStencilElement {
    }
    var HTMLSyDleGoodInpElement: {
        prototype: HTMLSyDleGoodInpElement;
        new (): HTMLSyDleGoodInpElement;
    };
    interface HTMLSyDleGoodLcpImageElement extends Components.SyDleGoodLcpImage, HTMLStencilElement {
    }
    var HTMLSyDleGoodLcpImageElement: {
        prototype: HTMLSyDleGoodLcpImageElement;
        new (): HTMLSyDleGoodLcpImageElement;
    };
    interface HTMLSyDleGoodLcpWillloadElement extends Components.SyDleGoodLcpWillload, HTMLStencilElement {
    }
    var HTMLSyDleGoodLcpWillloadElement: {
        prototype: HTMLSyDleGoodLcpWillloadElement;
        new (): HTMLSyDleGoodLcpWillloadElement;
    };
    interface HTMLSyDleMediumLcpWillloadElement extends Components.SyDleMediumLcpWillload, HTMLStencilElement {
    }
    var HTMLSyDleMediumLcpWillloadElement: {
        prototype: HTMLSyDleMediumLcpWillloadElement;
        new (): HTMLSyDleMediumLcpWillloadElement;
    };
    interface HTMLElementTagNameMap {
        "sy-dle-app-root": HTMLSyDleAppRootElement;
        "sy-dle-bad-cls": HTMLSyDleBadClsElement;
        "sy-dle-bad-inp": HTMLSyDleBadInpElement;
        "sy-dle-bad-lcp-image": HTMLSyDleBadLcpImageElement;
        "sy-dle-bad-lcp-willload": HTMLSyDleBadLcpWillloadElement;
        "sy-dle-example": HTMLSyDleExampleElement;
        "sy-dle-good-cls": HTMLSyDleGoodClsElement;
        "sy-dle-good-inp": HTMLSyDleGoodInpElement;
        "sy-dle-good-lcp-image": HTMLSyDleGoodLcpImageElement;
        "sy-dle-good-lcp-willload": HTMLSyDleGoodLcpWillloadElement;
        "sy-dle-medium-lcp-willload": HTMLSyDleMediumLcpWillloadElement;
    }
}
declare namespace LocalJSX {
    interface SyDleAppRoot {
    }
    interface SyDleBadCls {
    }
    interface SyDleBadInp {
    }
    interface SyDleBadLcpImage {
    }
    interface SyDleBadLcpWillload {
    }
    interface SyDleExample {
    }
    interface SyDleGoodCls {
    }
    interface SyDleGoodInp {
    }
    interface SyDleGoodLcpImage {
    }
    interface SyDleGoodLcpWillload {
    }
    interface SyDleMediumLcpWillload {
    }
    interface IntrinsicElements {
        "sy-dle-app-root": SyDleAppRoot;
        "sy-dle-bad-cls": SyDleBadCls;
        "sy-dle-bad-inp": SyDleBadInp;
        "sy-dle-bad-lcp-image": SyDleBadLcpImage;
        "sy-dle-bad-lcp-willload": SyDleBadLcpWillload;
        "sy-dle-example": SyDleExample;
        "sy-dle-good-cls": SyDleGoodCls;
        "sy-dle-good-inp": SyDleGoodInp;
        "sy-dle-good-lcp-image": SyDleGoodLcpImage;
        "sy-dle-good-lcp-willload": SyDleGoodLcpWillload;
        "sy-dle-medium-lcp-willload": SyDleMediumLcpWillload;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sy-dle-app-root": LocalJSX.SyDleAppRoot & JSXBase.HTMLAttributes<HTMLSyDleAppRootElement>;
            "sy-dle-bad-cls": LocalJSX.SyDleBadCls & JSXBase.HTMLAttributes<HTMLSyDleBadClsElement>;
            "sy-dle-bad-inp": LocalJSX.SyDleBadInp & JSXBase.HTMLAttributes<HTMLSyDleBadInpElement>;
            "sy-dle-bad-lcp-image": LocalJSX.SyDleBadLcpImage & JSXBase.HTMLAttributes<HTMLSyDleBadLcpImageElement>;
            "sy-dle-bad-lcp-willload": LocalJSX.SyDleBadLcpWillload & JSXBase.HTMLAttributes<HTMLSyDleBadLcpWillloadElement>;
            "sy-dle-example": LocalJSX.SyDleExample & JSXBase.HTMLAttributes<HTMLSyDleExampleElement>;
            "sy-dle-good-cls": LocalJSX.SyDleGoodCls & JSXBase.HTMLAttributes<HTMLSyDleGoodClsElement>;
            "sy-dle-good-inp": LocalJSX.SyDleGoodInp & JSXBase.HTMLAttributes<HTMLSyDleGoodInpElement>;
            "sy-dle-good-lcp-image": LocalJSX.SyDleGoodLcpImage & JSXBase.HTMLAttributes<HTMLSyDleGoodLcpImageElement>;
            "sy-dle-good-lcp-willload": LocalJSX.SyDleGoodLcpWillload & JSXBase.HTMLAttributes<HTMLSyDleGoodLcpWillloadElement>;
            "sy-dle-medium-lcp-willload": LocalJSX.SyDleMediumLcpWillload & JSXBase.HTMLAttributes<HTMLSyDleMediumLcpWillloadElement>;
        }
    }
}
