/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SyDleAppRoot {
    }
    interface SyDleBadCls {
    }
    interface SyDleBadInp {
    }
    interface SyDleBadLcpImage {
    }
    interface SyDleBadLcpWillload {
    }
    interface SyDleBadRender {
    }
    interface SyDleDetachedDomLeak {
    }
    interface SyDleDetachedDomLeakFixed {
    }
    interface SyDleExample {
    }
    interface SyDleGoodCls {
    }
    interface SyDleGoodInp {
    }
    interface SyDleGoodLcpImage {
    }
    interface SyDleGoodLcpWillload {
    }
    interface SyDleGoodRender {
    }
    interface SyDleJank {
    }
    interface SyDleLazy {
    }
    interface SyDleLazyImage {
        "alt": string;
        "disableLazy": boolean;
        "src": string;
    }
    interface SyDleListItem {
        "value": {id: number};
    }
    interface SyDleMediumLcpWillload {
    }
    interface SyDleNoJank {
    }
    interface SyDleNoLazy {
    }
}
declare global {
    interface HTMLSyDleAppRootElement extends Components.SyDleAppRoot, HTMLStencilElement {
    }
    var HTMLSyDleAppRootElement: {
        prototype: HTMLSyDleAppRootElement;
        new (): HTMLSyDleAppRootElement;
    };
    interface HTMLSyDleBadClsElement extends Components.SyDleBadCls, HTMLStencilElement {
    }
    var HTMLSyDleBadClsElement: {
        prototype: HTMLSyDleBadClsElement;
        new (): HTMLSyDleBadClsElement;
    };
    interface HTMLSyDleBadInpElement extends Components.SyDleBadInp, HTMLStencilElement {
    }
    var HTMLSyDleBadInpElement: {
        prototype: HTMLSyDleBadInpElement;
        new (): HTMLSyDleBadInpElement;
    };
    interface HTMLSyDleBadLcpImageElement extends Components.SyDleBadLcpImage, HTMLStencilElement {
    }
    var HTMLSyDleBadLcpImageElement: {
        prototype: HTMLSyDleBadLcpImageElement;
        new (): HTMLSyDleBadLcpImageElement;
    };
    interface HTMLSyDleBadLcpWillloadElement extends Components.SyDleBadLcpWillload, HTMLStencilElement {
    }
    var HTMLSyDleBadLcpWillloadElement: {
        prototype: HTMLSyDleBadLcpWillloadElement;
        new (): HTMLSyDleBadLcpWillloadElement;
    };
    interface HTMLSyDleBadRenderElement extends Components.SyDleBadRender, HTMLStencilElement {
    }
    var HTMLSyDleBadRenderElement: {
        prototype: HTMLSyDleBadRenderElement;
        new (): HTMLSyDleBadRenderElement;
    };
    interface HTMLSyDleDetachedDomLeakElement extends Components.SyDleDetachedDomLeak, HTMLStencilElement {
    }
    var HTMLSyDleDetachedDomLeakElement: {
        prototype: HTMLSyDleDetachedDomLeakElement;
        new (): HTMLSyDleDetachedDomLeakElement;
    };
    interface HTMLSyDleDetachedDomLeakFixedElement extends Components.SyDleDetachedDomLeakFixed, HTMLStencilElement {
    }
    var HTMLSyDleDetachedDomLeakFixedElement: {
        prototype: HTMLSyDleDetachedDomLeakFixedElement;
        new (): HTMLSyDleDetachedDomLeakFixedElement;
    };
    interface HTMLSyDleExampleElement extends Components.SyDleExample, HTMLStencilElement {
    }
    var HTMLSyDleExampleElement: {
        prototype: HTMLSyDleExampleElement;
        new (): HTMLSyDleExampleElement;
    };
    interface HTMLSyDleGoodClsElement extends Components.SyDleGoodCls, HTMLStencilElement {
    }
    var HTMLSyDleGoodClsElement: {
        prototype: HTMLSyDleGoodClsElement;
        new (): HTMLSyDleGoodClsElement;
    };
    interface HTMLSyDleGoodInpElement extends Components.SyDleGoodInp, HTMLStencilElement {
    }
    var HTMLSyDleGoodInpElement: {
        prototype: HTMLSyDleGoodInpElement;
        new (): HTMLSyDleGoodInpElement;
    };
    interface HTMLSyDleGoodLcpImageElement extends Components.SyDleGoodLcpImage, HTMLStencilElement {
    }
    var HTMLSyDleGoodLcpImageElement: {
        prototype: HTMLSyDleGoodLcpImageElement;
        new (): HTMLSyDleGoodLcpImageElement;
    };
    interface HTMLSyDleGoodLcpWillloadElement extends Components.SyDleGoodLcpWillload, HTMLStencilElement {
    }
    var HTMLSyDleGoodLcpWillloadElement: {
        prototype: HTMLSyDleGoodLcpWillloadElement;
        new (): HTMLSyDleGoodLcpWillloadElement;
    };
    interface HTMLSyDleGoodRenderElement extends Components.SyDleGoodRender, HTMLStencilElement {
    }
    var HTMLSyDleGoodRenderElement: {
        prototype: HTMLSyDleGoodRenderElement;
        new (): HTMLSyDleGoodRenderElement;
    };
    interface HTMLSyDleJankElement extends Components.SyDleJank, HTMLStencilElement {
    }
    var HTMLSyDleJankElement: {
        prototype: HTMLSyDleJankElement;
        new (): HTMLSyDleJankElement;
    };
    interface HTMLSyDleLazyElement extends Components.SyDleLazy, HTMLStencilElement {
    }
    var HTMLSyDleLazyElement: {
        prototype: HTMLSyDleLazyElement;
        new (): HTMLSyDleLazyElement;
    };
    interface HTMLSyDleLazyImageElement extends Components.SyDleLazyImage, HTMLStencilElement {
    }
    var HTMLSyDleLazyImageElement: {
        prototype: HTMLSyDleLazyImageElement;
        new (): HTMLSyDleLazyImageElement;
    };
    interface HTMLSyDleListItemElement extends Components.SyDleListItem, HTMLStencilElement {
    }
    var HTMLSyDleListItemElement: {
        prototype: HTMLSyDleListItemElement;
        new (): HTMLSyDleListItemElement;
    };
    interface HTMLSyDleMediumLcpWillloadElement extends Components.SyDleMediumLcpWillload, HTMLStencilElement {
    }
    var HTMLSyDleMediumLcpWillloadElement: {
        prototype: HTMLSyDleMediumLcpWillloadElement;
        new (): HTMLSyDleMediumLcpWillloadElement;
    };
    interface HTMLSyDleNoJankElement extends Components.SyDleNoJank, HTMLStencilElement {
    }
    var HTMLSyDleNoJankElement: {
        prototype: HTMLSyDleNoJankElement;
        new (): HTMLSyDleNoJankElement;
    };
    interface HTMLSyDleNoLazyElement extends Components.SyDleNoLazy, HTMLStencilElement {
    }
    var HTMLSyDleNoLazyElement: {
        prototype: HTMLSyDleNoLazyElement;
        new (): HTMLSyDleNoLazyElement;
    };
    interface HTMLElementTagNameMap {
        "sy-dle-app-root": HTMLSyDleAppRootElement;
        "sy-dle-bad-cls": HTMLSyDleBadClsElement;
        "sy-dle-bad-inp": HTMLSyDleBadInpElement;
        "sy-dle-bad-lcp-image": HTMLSyDleBadLcpImageElement;
        "sy-dle-bad-lcp-willload": HTMLSyDleBadLcpWillloadElement;
        "sy-dle-bad-render": HTMLSyDleBadRenderElement;
        "sy-dle-detached-dom-leak": HTMLSyDleDetachedDomLeakElement;
        "sy-dle-detached-dom-leak-fixed": HTMLSyDleDetachedDomLeakFixedElement;
        "sy-dle-example": HTMLSyDleExampleElement;
        "sy-dle-good-cls": HTMLSyDleGoodClsElement;
        "sy-dle-good-inp": HTMLSyDleGoodInpElement;
        "sy-dle-good-lcp-image": HTMLSyDleGoodLcpImageElement;
        "sy-dle-good-lcp-willload": HTMLSyDleGoodLcpWillloadElement;
        "sy-dle-good-render": HTMLSyDleGoodRenderElement;
        "sy-dle-jank": HTMLSyDleJankElement;
        "sy-dle-lazy": HTMLSyDleLazyElement;
        "sy-dle-lazy-image": HTMLSyDleLazyImageElement;
        "sy-dle-list-item": HTMLSyDleListItemElement;
        "sy-dle-medium-lcp-willload": HTMLSyDleMediumLcpWillloadElement;
        "sy-dle-no-jank": HTMLSyDleNoJankElement;
        "sy-dle-no-lazy": HTMLSyDleNoLazyElement;
    }
}
declare namespace LocalJSX {
    interface SyDleAppRoot {
    }
    interface SyDleBadCls {
    }
    interface SyDleBadInp {
    }
    interface SyDleBadLcpImage {
    }
    interface SyDleBadLcpWillload {
    }
    interface SyDleBadRender {
    }
    interface SyDleDetachedDomLeak {
    }
    interface SyDleDetachedDomLeakFixed {
    }
    interface SyDleExample {
    }
    interface SyDleGoodCls {
    }
    interface SyDleGoodInp {
    }
    interface SyDleGoodLcpImage {
    }
    interface SyDleGoodLcpWillload {
    }
    interface SyDleGoodRender {
    }
    interface SyDleJank {
    }
    interface SyDleLazy {
    }
    interface SyDleLazyImage {
        "alt"?: string;
        "disableLazy"?: boolean;
        "src"?: string;
    }
    interface SyDleListItem {
        "value"?: {id: number};
    }
    interface SyDleMediumLcpWillload {
    }
    interface SyDleNoJank {
    }
    interface SyDleNoLazy {
    }
    interface IntrinsicElements {
        "sy-dle-app-root": SyDleAppRoot;
        "sy-dle-bad-cls": SyDleBadCls;
        "sy-dle-bad-inp": SyDleBadInp;
        "sy-dle-bad-lcp-image": SyDleBadLcpImage;
        "sy-dle-bad-lcp-willload": SyDleBadLcpWillload;
        "sy-dle-bad-render": SyDleBadRender;
        "sy-dle-detached-dom-leak": SyDleDetachedDomLeak;
        "sy-dle-detached-dom-leak-fixed": SyDleDetachedDomLeakFixed;
        "sy-dle-example": SyDleExample;
        "sy-dle-good-cls": SyDleGoodCls;
        "sy-dle-good-inp": SyDleGoodInp;
        "sy-dle-good-lcp-image": SyDleGoodLcpImage;
        "sy-dle-good-lcp-willload": SyDleGoodLcpWillload;
        "sy-dle-good-render": SyDleGoodRender;
        "sy-dle-jank": SyDleJank;
        "sy-dle-lazy": SyDleLazy;
        "sy-dle-lazy-image": SyDleLazyImage;
        "sy-dle-list-item": SyDleListItem;
        "sy-dle-medium-lcp-willload": SyDleMediumLcpWillload;
        "sy-dle-no-jank": SyDleNoJank;
        "sy-dle-no-lazy": SyDleNoLazy;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sy-dle-app-root": LocalJSX.SyDleAppRoot & JSXBase.HTMLAttributes<HTMLSyDleAppRootElement>;
            "sy-dle-bad-cls": LocalJSX.SyDleBadCls & JSXBase.HTMLAttributes<HTMLSyDleBadClsElement>;
            "sy-dle-bad-inp": LocalJSX.SyDleBadInp & JSXBase.HTMLAttributes<HTMLSyDleBadInpElement>;
            "sy-dle-bad-lcp-image": LocalJSX.SyDleBadLcpImage & JSXBase.HTMLAttributes<HTMLSyDleBadLcpImageElement>;
            "sy-dle-bad-lcp-willload": LocalJSX.SyDleBadLcpWillload & JSXBase.HTMLAttributes<HTMLSyDleBadLcpWillloadElement>;
            "sy-dle-bad-render": LocalJSX.SyDleBadRender & JSXBase.HTMLAttributes<HTMLSyDleBadRenderElement>;
            "sy-dle-detached-dom-leak": LocalJSX.SyDleDetachedDomLeak & JSXBase.HTMLAttributes<HTMLSyDleDetachedDomLeakElement>;
            "sy-dle-detached-dom-leak-fixed": LocalJSX.SyDleDetachedDomLeakFixed & JSXBase.HTMLAttributes<HTMLSyDleDetachedDomLeakFixedElement>;
            "sy-dle-example": LocalJSX.SyDleExample & JSXBase.HTMLAttributes<HTMLSyDleExampleElement>;
            "sy-dle-good-cls": LocalJSX.SyDleGoodCls & JSXBase.HTMLAttributes<HTMLSyDleGoodClsElement>;
            "sy-dle-good-inp": LocalJSX.SyDleGoodInp & JSXBase.HTMLAttributes<HTMLSyDleGoodInpElement>;
            "sy-dle-good-lcp-image": LocalJSX.SyDleGoodLcpImage & JSXBase.HTMLAttributes<HTMLSyDleGoodLcpImageElement>;
            "sy-dle-good-lcp-willload": LocalJSX.SyDleGoodLcpWillload & JSXBase.HTMLAttributes<HTMLSyDleGoodLcpWillloadElement>;
            "sy-dle-good-render": LocalJSX.SyDleGoodRender & JSXBase.HTMLAttributes<HTMLSyDleGoodRenderElement>;
            "sy-dle-jank": LocalJSX.SyDleJank & JSXBase.HTMLAttributes<HTMLSyDleJankElement>;
            "sy-dle-lazy": LocalJSX.SyDleLazy & JSXBase.HTMLAttributes<HTMLSyDleLazyElement>;
            "sy-dle-lazy-image": LocalJSX.SyDleLazyImage & JSXBase.HTMLAttributes<HTMLSyDleLazyImageElement>;
            "sy-dle-list-item": LocalJSX.SyDleListItem & JSXBase.HTMLAttributes<HTMLSyDleListItemElement>;
            "sy-dle-medium-lcp-willload": LocalJSX.SyDleMediumLcpWillload & JSXBase.HTMLAttributes<HTMLSyDleMediumLcpWillloadElement>;
            "sy-dle-no-jank": LocalJSX.SyDleNoJank & JSXBase.HTMLAttributes<HTMLSyDleNoJankElement>;
            "sy-dle-no-lazy": LocalJSX.SyDleNoLazy & JSXBase.HTMLAttributes<HTMLSyDleNoLazyElement>;
        }
    }
}
