/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SyDleAppRoot {
    }
    interface SyDleExample {
    }
}
declare global {
    interface HTMLSyDleAppRootElement extends Components.SyDleAppRoot, HTMLStencilElement {
    }
    var HTMLSyDleAppRootElement: {
        prototype: HTMLSyDleAppRootElement;
        new (): HTMLSyDleAppRootElement;
    };
    interface HTMLSyDleExampleElement extends Components.SyDleExample, HTMLStencilElement {
    }
    var HTMLSyDleExampleElement: {
        prototype: HTMLSyDleExampleElement;
        new (): HTMLSyDleExampleElement;
    };
    interface HTMLElementTagNameMap {
        "sy-dle-app-root": HTMLSyDleAppRootElement;
        "sy-dle-example": HTMLSyDleExampleElement;
    }
}
declare namespace LocalJSX {
    interface SyDleAppRoot {
    }
    interface SyDleExample {
    }
    interface IntrinsicElements {
        "sy-dle-app-root": SyDleAppRoot;
        "sy-dle-example": SyDleExample;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sy-dle-app-root": LocalJSX.SyDleAppRoot & JSXBase.HTMLAttributes<HTMLSyDleAppRootElement>;
            "sy-dle-example": LocalJSX.SyDleExample & JSXBase.HTMLAttributes<HTMLSyDleExampleElement>;
        }
    }
}
